apiVersion: v1
kind: ReplicationController
metadata:
  name: test
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      serviceAccount: YOUR
      containers:
      - name: test
        image: ${docker-registry}/${docker-namespace}/test:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080